[package]
name = "rtail"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
notify = { version = "6.1.1", default-features = false, features = ["macos_fsevent"] }
ratatui = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
